### ISSUE TITLE
Regarding Code

### ISSUE THREAD

**Issue by nitinmaru** [clebio/oculus-opencv#1]
HI
I am working on same for my college project if you help me for same using openCV and WIndows Visual studio 2013 
i am confused how to start and from where to start
I seen many examples but it all seems some confusing codes

It would be great if you can help me 
looking forward to hear from you
Thanks

**Comment by clebio** [comment]
Hi Nitin,

Start with the unit tests: 
https://github.com/clebio/oculus-opencv/blob/master/test.py
https://github.com/clebio/oculus-opencv/tree/master/tests
Figure out what they're testing and what part of the source they're calling. Best of luck!

**Comment by clebio** [comment]
let me know if you need anything else!
